### ISSUE TITLE
JSON changes

### ISSUE THREAD

**Issue by modicr** [boris-savic/python-furs-fiscal#10]
Please correct to:

```
        message['InvoiceRequest']['Invoice']['SubsequentSubmit'] = True

        message['InvoiceRequest']['Invoice']['CustomerVATNumber'] = customer_vat_number
```

Vir:
http://www.datoteke.fu.gov.si/dpr/files/wsdl_v1/FiscalVerificationSchema.json

**Comment by boris-savic** [comment]
Changed. Will release new version to PyPi later this week.

Thanks!

**Comment by modicr** [comment]
Thanks for your library. BTW, this is my first python project and I really like your implementation of classes.
