### ISSUE TITLE
ClosingTag (BusinessPremise)

### ISSUE THREAD

**Issue by modicr** [boris-savic/python-furs-fiscal#11]
Hello!

Please add support for ClosingTag:

> Vpiše se podatek o zaprtju poslovnega prostora, če gre za trajno zaprtje. Možna je vrednost »Z«. Po zaprtju v tem poslovnem prostoru ni več možno izdajati računov in računov z oznako tega poslovnega prostora ni več možno posredovati davčnemu organu. / The data is entered about the closure of business premises if the closure is permanent. The possible value is »Z«. After closure issuing invoices is not possible anymore in these business premises and it is not possible to submit invoices to the tax authority with the mark of these business premises.

```
def _build_common_message_body(*args, **kwargs):
    data = dict()

    clotag = kwargs['closing_tag']

    data['BusinessPremiseRequest'] = {
        'Header': FURSBusinessPremiseAPI._prepare_business_premise_request_header(),
        'BusinessPremise': {
            'TaxNumber': kwargs['tax_number'],
            'BusinessPremiseID': kwargs['premise_id'],
            'ValidityDate': kwargs['validity_date'].strftime("%Y-%m-%d"),
            'ClosingTag': clotag,
            'SpecialNotes': kwargs['special_notes'],
            'SoftwareSupplier': [
                FURSBusinessPremiseAPI._prepare_software_supplier_json(kwargs['software_supplier_tax_number'],
                                                                       kwargs['foreign_software_supplier_name'])
            ],
            'BPIdentifier': {}
        }
    }

    if (clotag is None) or clotag=='':
        data['BusinessPremiseRequest']['BusinessPremise'].pop('ClosingTag')


    return data
```

**Comment by boris-savic** [comment]
24.11 je bil "ClosingTag" odstranjen iz uradne dokumentacije,

http://www.datoteke.fu.gov.si/dpr/files/TehnicnaDokumentacijaVer1.6.pdf  --> glej spremembe dokumenta

**Comment by modicr** [comment]
Hmm, kako pa deaktiviramo poslovni prostor?

**Comment by boris-savic** [comment]
Ga ne. Nehaš pošiljat račune gor za ta prostor in to je to.
