### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by Majstr** [boris-savic/python-furs-fiscal#3]
Since commits from 12.nov I get openssl error. 
Exception return: "[('system library', 'fopen', 'Broken pipe'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]"

**Comment by boris-savic** [comment]
Hi Majstr,

I can't reproduce your error, can you provide a bit more context? 

PS: Are you using the release from PyPi or directly cloning the repo into your project?

**Comment by Majstr** [comment]
I cloned the repo becouse I want to make some changes about reading certificate. I am using Windows machine. Maybe is problem with temporary file. I already have problem with temp files on Windows.

https://bugs.python.org/issue14243

**Comment by boris-savic** [comment]
Thanks. Will check for a possible fix on Windows.

**Comment by Majstr** [comment]
If I put back flag "delete=False" it is working again.

**Comment by boris-savic** [comment]
I'm guessting this is no longer an issue?
