### ISSUE TITLE
ReferenceInvoice error

### ISSUE THREAD

**Issue by Majstr** [boris-savic/python-furs-fiscal#5]
When I try to send data for changed invoice I get error "S002 - Sporočilo ni v skladu s shemo JSON". It is problem with these variables:
- reference_invoice_number
- reference_invoice_business_premise_id
- reference_invoice_electronic_device_id
- reference_invoice_issued_date

If I remove this values everything works fine. Variable values are the same as this:
- invoice_number
- business_premise_id
- electronic_device_id
- issued_date

**Comment by boris-savic** [comment]
Will check your pull request later this week.

**Comment by boris-savic** [comment]
Fixed in commit #6

**Comment by boris-savic** [comment]
Fixed in commit #6
